-- Remediation 02. Dedicated Review Activator DEV only.
-- Generated by Supabase CLI; historical migrations remain unchanged.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '30s';

-- Stop if the known legacy scheduler has not been paused by the operator.
do $$
begin
  if exists (select 1 from cron.job where jobname='review-provider-due-check-hourly' and active) then
    raise exception 'PAUSE_REVIEW_DEV_SCHEDULER_FIRST';
  end if;
end;
$$;

-- Retired compatibility signature: no mutation even after an accidental future grant.
create or replace function public.review_public_request_due_syncs(p_token text)
returns integer language plpgsql security invoker set search_path = ''
as $$
begin
  raise exception using errcode = '42501', message = 'PUBLIC_SYNC_DISABLED';
end;
$$;
revoke all on function public.review_public_request_due_syncs(text) from public, anon, authenticated, service_role;

-- Replace the existing engine, do not introduce a parallel one.
-- Breaking SQL signature: all scheduler callers must now supply a trusted company UUID.
-- No CASCADE: unexpected dependencies abort this migration.
drop function public.review_enqueue_due_syncs();
create function public.review_enqueue_due_syncs(p_company_id uuid)
returns integer language plpgsql security invoker set search_path = ''
as $$
declare
  r record;
  queued integer := 0;
  run_status text;
begin
  if p_company_id is null then
    raise exception using errcode = '22023', message = 'SYNC_COMPANY_REQUIRED';
  end if;
  for r in
    select * from public.review_provider_connections
    where company_id = p_company_id
      and enabled = true and status <> 'PAUSED' and next_sync_at <= now()
    for update skip locked
  loop
    run_status := case when r.status = 'READY' then 'QUEUED' else 'SKIPPED_NOT_CONFIGURED' end;
    insert into public.review_sync_runs(
      provider_connection_id, provider, status, requested_at, finished_at, error, meta
    ) values (
      r.id, r.provider, run_status, now(),
      case when run_status = 'SKIPPED_NOT_CONFIGURED' then now() else null end,
      case when run_status = 'SKIPPED_NOT_CONFIGURED' then 'Provider access is not configured yet' else null end,
      jsonb_build_object('source','server-scheduler','interval_minutes',r.sync_interval_minutes)
    );
    update public.review_provider_connections
    set last_sync_requested_at = now(),
        next_sync_at = now() + make_interval(mins => r.sync_interval_minutes),
        updated_at = now()
    where id = r.id and company_id = p_company_id;
    queued := queued + 1;
  end loop;
  return queued;
end;
$$;
revoke all on function public.review_enqueue_due_syncs(uuid) from public, anon, authenticated;
grant execute on function public.review_enqueue_due_syncs(uuid) to service_role, postgres;

-- Public status is intentionally read-only; do not expose free-form backend errors.
create or replace function public.review_public_sync_status(p_token text)
returns table(
  provider text, connection_status text, sync_interval_minutes integer,
  last_sync_requested_at timestamptz, last_success_at timestamptz,
  next_sync_at timestamptz, last_error text
)
language sql stable security definer set search_path = ''
as $$
  select pc.provider, pc.status, pc.sync_interval_minutes,
         pc.last_sync_requested_at, pc.last_success_at, pc.next_sync_at,
         case when pc.last_error is null then null::text else 'PROVIDER_SYNC_ERROR'::text end
  from public.review_provider_connections pc
  join public.review_locations l on l.company_id = pc.company_id
  join public.review_qr_sources q on q.location_id = l.id
  where q.public_token = p_token and q.active = true
  order by pc.provider;
$$;
revoke all on function public.review_public_sync_status(text) from public;
grant execute on function public.review_public_sync_status(text) to anon, authenticated, service_role;
notify pgrst, 'reload schema';
commit;
